from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

from ..jsonio import write_json


def build_suggestion_patches(design: dict[str, Any], suggestions: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build deterministic JSON Patch-style operations for check suggestions."""
    used = {
        str(check.get("id"))
        for check in (design.get("checks") or [])
        if isinstance(check, dict) and check.get("id")
    }
    feature_indexes = {
        str(feature.get("id")): index
        for index, feature in enumerate(design.get("features") or [])
        if isinstance(feature, dict) and feature.get("id")
    }

    patches: list[dict[str, Any]] = []
    for suggestion in suggestions:
        template = suggestion.get("template")
        feature_id = str(suggestion.get("feature", ""))
        if not isinstance(template, dict) or feature_id not in feature_indexes:
            continue

        check = deepcopy(template)
        check_id = _unique_check_id(str(check.get("id") or f"{feature_id}_check"), used)
        check["id"] = check_id
        used.add(check_id)

        feature_index = feature_indexes[feature_id]
        feature = (design.get("features") or [])[feature_index]
        if not isinstance(feature.get("checks"), list):
            patches.append({"op": "add", "path": f"/features/{feature_index}/checks", "value": []})
        patches.append({"op": "add", "path": "/checks/-", "value": check})
        patches.append({"op": "add", "path": f"/features/{feature_index}/checks/-", "value": check_id})
    return patches


def apply_suggestion_patches(design: dict[str, Any], patches: list[dict[str, Any]], path: Path) -> dict[str, Any]:
    """Apply the limited patch shape generated by build_suggestion_patches."""
    updated = deepcopy(design)
    if not isinstance(updated.get("checks"), list):
        updated["checks"] = []
    for patch in patches:
        if patch.get("op") != "add":
            raise ValueError(f"unsupported patch op: {patch.get('op')}")
        _json_pointer_add(updated, str(patch.get("path", "")), deepcopy(patch.get("value")))
    write_json(path, updated)
    return updated


def _unique_check_id(base: str, used: set[str]) -> str:
    candidate = base
    index = 2
    while candidate in used:
        candidate = f"{base}_{index}"
        index += 1
    return candidate


def _json_pointer_add(document: Any, pointer: str, value: Any) -> None:
    if not pointer.startswith("/"):
        raise ValueError(f"invalid JSON pointer: {pointer}")
    parts = [_unescape(part) for part in pointer.lstrip("/").split("/")]
    parent = document
    for part in parts[:-1]:
        parent = _descend(parent, part)
    key = parts[-1]
    if isinstance(parent, list):
        if key == "-":
            parent.append(value)
        else:
            parent.insert(int(key), value)
        return
    if isinstance(parent, dict):
        parent[key] = value
        return
    raise ValueError(f"cannot add through non-container at {pointer}")


def _descend(value: Any, key: str) -> Any:
    if isinstance(value, list):
        return value[int(key)]
    if isinstance(value, dict):
        if key not in value:
            value[key] = {}
        return value[key]
    raise ValueError(f"cannot descend through non-container at {key}")


def _unescape(part: str) -> str:
    return part.replace("~1", "/").replace("~0", "~")
